### PR TITLE
Reduced hierarchy levels in Powertrain branch

### PR DESCRIPTION
**Pull request by dakrbo**
For issue #187 : simple PR that removes a couple of directories from the Powertrain branch

### CODE REVIEW

**Review by SebastianSchildt — APPROVED** [review]
"Works for me" 😼

**Review by danielwilms — APPROVED** [review]

**Review by chheis — APPROVED** [review]

**Comment by chheis** [comment]
approved

**Comment by chheis** [comment]
@UlfBj @gunnarx Can you merge the pull request? We approved this 2 weeks back. Thx

**Review by UlfBj — APPROVED** [review]

**Comment by danielwilms** [comment]
Merged, with enough approvals and discussed.

**Pull request merged**
