### PR TITLE
add vspec2yaml.py from vss-tools

### PR DESCRIPTION
**Pull request by crea7or**
adding vspec2yaml.py from vss-tools pr #96

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Should be merged, if vspec2ymal is merged and workflow runs

**Comment by erikbosch** [comment]
@gunnarx - will you update the vss-tools submodule in vss so that vspec2yaml? One done I believe a re-run of this PR (possibly after rebasing) should succeed

**Comment by gunnarx** [comment]
Rebased on top of #340.

**Comment by gunnarx** [comment]
@erikbosch  You're right, it succeeded.

**Comment by gunnarx** [comment]
#340 was merged so rebased again.

**Pull request merged**
