### PR TITLE
cnative tool refactoring.

### PR DESCRIPTION
**Pull request by UlfBj**

### CODE REVIEW

**Comment by danielwilms** [comment]
@UlfBj, could you briefly describe what the goal of the commit is and why it needs to be refactors. Just a couple of words, so that it's easier to review? 

Maybe we should try to release it, before we split the tools, @gunnarx ?

**Comment by UlfBj** [comment]
The refactoring was mainly done in the "tree manager" code that is e. g. used in the W3C Gen2 server impl github project. Besides improving code redability, it also simplifies the coding effort for this "tree manager" to be implemented to manage other tree formats than the cnative format, such as JSON etc.

**Comment by danielwilms** [comment]
@magnusfeuer, checks the proposal and we decide how to move forward.

**Comment by gunnarx** [comment]
Since I did the tree split I would prefer to wait until we merge #144 and introduce this change in the vss-tools repository instead.  Otherwise I have to redo the tree split again, or some other complicated procedure that I can't think of now(probably possible with some tricks).  I prefer to avoid that however.

**Comment by gunnarx** [comment]
More work done on #144 now, so even more reason :)   @UlfBj Please recreate this PR in the https://github.com/GENIVI/vss-tools repository instead.

**Comment by danielwilms** [comment]
PR for tools repo recreated

**Comment by UlfBj** [comment]
PR "cnative tool refactoring. #1" created on
https://github.com/GENIVI/vss-tools



Den tis 7 apr. 2020 kl 19:35 skrev danielwilms <notifications@github.com>:

**Pull request closed without merging**
