### PR TITLE
Type fix: uint32 -> int32 for signed values

### PR DESCRIPTION
**Pull request by crea7or**
my validation tool found this error since I use this signals database as a sample

### CODE REVIEW

**Review by erikbosch — APPROVED** [review]
Good catch

**Comment by SebastianSchildt** [comment]
@gunnarx  or @danielwilms  pls approve the gh action workflow, you seem to be the only ones with those rights

**Comment by erikbosch** [comment]
Discussed at meeting 2021-08-10, looks good, can be merged if tests run succesfully

**Review by SebastianSchildt — APPROVED** [review]

**Comment by gunnarx** [comment]
I clicked merge because we decided it is OK, but for the future I would give this feedback.

Instead of "Type fix for signed values" it should say something like: "Motor.Rpm: Change to signed integer".
Please try to follow best practices for commit messages.  Most open-source project guidelines are very similar.  Here is a good summary: https://wiki.gnome.org/Git/CommitMessages

**Pull request merged**
