### PR TITLE
Makefile updated to support native tool.

### PR DESCRIPTION
**Pull request by UlfBj**
If the PR introducing the native tool n the VSS-Tools repo is accepted, then this update is needed. 
If not, it is to be rejected.

### CODE REVIEW

**Comment by UlfBj** [comment]
The tool name is changed to binary.

**Comment by danielwilms** [comment]
Checked it against the vss-tools master branch of Ulf, used in the[ corresponding PR](https://github.com/GENIVI/vss-tools/pull/28) and it works.

**Review by danielwilms — APPROVED** [review]

**Comment by gunnarx** [comment]
Squashed the three commits together, and rebased on latest master.  Awaiting build check and will then merge.

**Comment by gunnarx** [comment]
Travis file was not building the target all, only a few selected ones.  I pushed a commit to fix this and now we can again do the build check.

**Comment by gunnarx** [comment]
OK, the PR also needs the update of the vss-tools submodule to include the binary tool.
(Can be done now that it is merged).  So we try again...

**Comment by gunnarx** [comment]
One of the files had the wrong Pa(scal) unit.  This is unrelated to this PR but fixed now so we can get a successful build check (hopefully).   I'm not sure why this was not noticed before, but as noted above I changed  .travis build to build "all" now.  I'm still surprised that what we DID build before was not checking the units(??)

**Pull request merged**
