### PR TITLE
vss-tools: Bump submodule

### PR DESCRIPTION
**Pull request by gunnarx**
New PR to bump submodule to latest master of vss-tools.  According to travis check on vss-tools it seems to build OK (that is not yet merged to vss-tools master, but it seems to work:  https://travis-ci.org/github/gunnarx/vss-tools/builds/723152253)
We don't really need to merge it before updating, because it doesn't affect the Travis check on **this** repo.

The commit also includes a shortlog of the changes as follows:  (A good practice we may want to adopt)
----------

  14efa2e Changed N.m to Nm
  67b13c6 Bugfix: Add previously removed method
  b6814db Typo in Enum Handling for UInt64 fixed
  4497a47 Added typesafe parsing using anytree, including tests and ReadMe.MD Migrated csv parser for demonstration purposes
  55ae597 Merge pull request #4 from magnusfeuer/master
  7039c86 Fixes issue https://github.com/GENIVI/vss-tools/pull/4#issuecomment-636300056
  51757b5 cnative tool refactoring.
  7fbe9ce Adding Licence file
  416da82 Introduced dictionary-parsing vspec.py.

Signed-off-by: Gunnar Andersson <gandersson@genivi.org>

### CODE REVIEW

**Comment by gunnarx** [comment]
#178 might be obsoleted by this, at least if everyone agrees to not do "update --remote" on the submodule, at least not yet..

**Comment by gunnarx** [comment]
Sorry, we need this commit also: https://github.com/GENIVI/vss-tools/pull/19/commits/b6c4987a0b3ac924f4f7750cce53c5055f8927dd (fix python2/python3 calling convention) 
for the travis build to succeed also here.  It is included in the vss-tools Travis PR.

I propose to merge the travis PR in vss-tools : https://github.com/GENIVI/vss-tools/pull/19  and then bump this one more step.  

Please give your input on each part  
(using python2/3 env c272f26b145abac1b3065b9729cb8c8a33670285 OK, not OK?
Travis file in https://github.com/GENIVI/vss-tools/pull/19)

**Comment by danielwilms** [comment]
I have to change the yaml accordingly, because before it just had pyyaml as dependency, now it's all in the requirements.txt.

**Comment by gunnarx** [comment]
OK, added a commit to install with requirements.txt.  Now the PR will build successfully.

**Review by danielwilms — APPROVED** [review]

**Comment by danielwilms** [comment]
Merge, as discussed in the meeting on 2020/09/01.

**Pull request merged**
