### PR TITLE
WIP Vssnative

### PR DESCRIPTION
**Pull request by UlfBj**

### CODE REVIEW

**Comment by UlfBj** [comment]
The pull request #78 is now updated with the vspec file differences between commits 03b660c (April 9) and f0fd40 (Aug 3).

**Comment by gunnarx** [comment]
I have done a local merge of this which resolves the conflicts simply by forcing all the changes on Ulf's branch (i.e. this PR) to take precedence, just as we discussed earlier.  The last commit "diff between commits 03b660c and f0fd40e" suggests that doing that ought to give us the intended/wanted combined result.

The only question I had before pushing the result is if I should push it to master, or if we are looking to make the new "2.0" branch first and put it there instead.  

In addition, I could also push the merge result back to UlfBj/vssnative branch - the result of that is purely cosmetic -- that GitHub will recognize this PR as "merged" rather than just "closed".  Actually when I think about it, it should be the right thing because then if @UlfBj  continues more work on the same branch then it will not be on an outdated basis.

**Comment by danielwilms** [comment]
Hi @UlfBj, @gunnarx:  I did a rebase, so that it can be merged and will add my changes now. Please don't merge till then.

**Comment by danielwilms** [comment]
@UlfBj, @gunnarx, @klotzbenjamin: Could you please review this one and give your +1 or add comments, so that we can merge it? Thanks so much!

**Comment by klotzbenjamin** [comment]
@danielwilms Do not forget to create the `v1` branch before merging to `master`

**Comment by danielwilms** [comment]
> Do not forget to create the v1 branch before merging to master

we can create the v1 branch from any commit. We have to agree on which that should be. I'll create an issue for that.

**Comment by danielwilms** [comment]
> There are some datatype instances starting with capital letters, such as Double, String, Intxx.
With that fixed, it is ready for me to approve.

@UlfBj I fixed it. Could you confirm, then we can merge.

**Pull request merged**
