### PR TITLE
Adding support for optional builds

### PR DESCRIPTION
**Pull request by erikbosch**
Currently not for merge

### CODE REVIEW

**Comment by erikbosch** [comment]
Suggested order of merge to avoid build problems:

First merge #263 
Then https://github.com/GENIVI/vss-tools/pull/49 shall hopefully pass travis test without build errors
Then this PR shall be updated with latest vss-tools and then merged

Sounds reasonable @gunnarx?

**Comment by erikbosch** [comment]
@gunnarx @danielwilms can anyone of you remove the "dontmerge" label. It is now a candidate for merge for the next vss-meeting (or earlier if we want to fix build errors for vss-tools PRs)

**Comment by gunnarx** [comment]
There was one change merged in between.   Updated the PR with the latest vss-tools so we avoid another change and added shortlog in message.

**Comment by gunnarx** [comment]
Looks good.  Build check is OK.  (travis_optional has an error but it does not fail the build check, as expected)

**Comment by gunnarx** [comment]
Ooops, looks like you managed to sneak a change in :)  No problem, we'll get them next time!

**Pull request merged**
