### PR TITLE
Changed VSS elements from YAML list to dictionary

### PR DESCRIPTION
**Pull request by danielwilms**
- Changed list entries in spec file with kudos to @magnusfeuer for providing the script
- Fixed documentation

Fixes: #149

Depends on: GENIVI/vss-tools#68

### CODE REVIEW

**Comment by danielwilms** [comment]
Checked diffs of all generated serialization and it turned out to be the same. Please double check!

**Review by SebastianSchildt — APPROVED** [review]
I ran this using the tools version from https://github.com/GENIVI/vss-tools/pull/67 cherry-picking eb9220041fb99fab0973b55a3cb11e011ef604d from https://github.com/GENIVI/vss-tools/pull/68 on top (git is magic, that even worked after the vspec->__init__.py rename ) 

I could generate a JSON file and the sha1sum did not change -> **Approved**

**Review by gunnarx — APPROVED** [review]
Thanks for testing it @SebastianSchildt . The changes to docs and spec files look exactly as expected too.

**Comment by gunnarx** [comment]
Rebased also this to include the GitHub actions build check.

**Comment by danielwilms** [comment]
@danielwilms update submodule and merge

**Comment by gunnarx** [comment]
Added an update of vss-tools so that collections fix is included.

**Comment by gunnarx** [comment]
Finally, it works now.

**Pull request merged**
